# ============================================================
# CONEXIÓN A LA BASE DE DATOS DE PUNTADA CREATIVA
# ============================================================
spring.datasource.url=jdbc:mysql://localhost:3306/proyecto_web?serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=0001

# Controladores JDBC de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ============================================================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ============================================================
# 'update' sincroniza tus clases Java automáticamente con las tablas de MySQL
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de comandos las consultas SQL ejecutadas en tiempo real
spring.jpa.show-sql=true

# Especifica el Dialecto para evitar el error de "Unable to determine Dialect"
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect